// Central data file for Abdul Zakir's portfolio

export const personalInfo = {
  name: "Abdul Zakir",
  firstName: "Abdul",
  lastName: "Zakir",
  initials: "AZ",
  title: "CS Student & Software Developer",
  location: "Islamabad, Pakistan",
  email: "zakirbulaidi@gmail.com",
  phone: "+92 300 1776024",
  github: "https://github.com/abzakir",
  linkedin: "https://www.linkedin.com/in/abdul-zakir-833793309",
  university: "FAST NUCES, Islamabad",
  degree: "BS Computer Science",
  expectedGrad: "2029",
  taglines: [
    "Software Developer",
    "AI Enthusiast",
    "Problem Solver",
    "Computer Vision Explorer",
    "Builder of Digital Experiences",
    "Future Software Engineer",
  ],
  bio: [
    "Second-year CS student at FAST NUCES — writing code that matters, leading teams that deliver, and building products that solve real problems.",
    "I sit at the intersection of technical depth and human creativity. Whether it's computer vision, game systems, or interactive web experiences, I build things that work and feel great.",
    "I believe in shipping real projects, not just studying them.",
  ],
  stats: [
    { value: "2+", label: "Years at FAST" },
    { value: "5+", label: "Projects Shipped" },
    { value: "3", label: "Languages Spoken" },
    { value: "8+", label: "Awards & Certs" },
  ],
  interests: [
    "Software Engineering", "Artificial Intelligence", "Computer Vision",
    "Linux", "Game Development", "System Design", "Problem Solving",
    "Public Speaking", "Leadership", "Product Building"
  ],
  languages: [
    { name: "English", level: "Professional Proficiency" },
    { name: "Urdu", level: "Native" },
    { name: "Sindhi", level: "Native" },
  ],
};

export const skills = {
  languages: [
    { name: "C", icon: "code", color: "#A8B9CC", desc: "Systems & low-level programming", image: "/c-logo.png" },
    { name: "C++", icon: "code2", color: "#00599C", desc: "OOP, game dev, performance-critical code", image: "/cpp-logo.png" },
    { name: "Python", icon: "terminal", color: "#3776AB", desc: "AI, automation, scripting", image: "/python-logo.jpg" },
    { name: "HTML", icon: "globe", color: "#E34F26", desc: "Semantic web structure", image: "/html-logo.png" },
    { name: "CSS", icon: "palette", color: "#1572B6", desc: "Responsive styling & animations", image: "/css-logo.png" },
  ],
  tools: [
    { name: "Git", icon: "git", color: "#F05032", desc: "Version control & collaboration" },
    { name: "GitHub", icon: "github", color: "#6E40C9", desc: "Open source & project hosting" },
    { name: "Linux", icon: "linux", color: "#FCC624", desc: "Command line & system ops" },
    { name: "VS Code", icon: "vscode", color: "#007ACC", desc: "Primary development environment" },
  ],
  libraries: [
    { name: "SFML", icon: "sfml", color: "#8CC445", desc: "2D graphics & game development" },
    { name: "MediaPipe", icon: "mediapipe", color: "#00897B", desc: "Real-time computer vision ML" },
  ],
};

export const education = [
  {
    institution: "FAST National University",
    degree: "BS Computer Science",
    period: "2025 – 2029",
    location: "Islamabad, Pakistan",
    details: "Second-year student. Coursework in DSA, OOP, systems programming, and software engineering.",
    type: "university",
    icon: "graduation",
  },
  {
    institution: "Aga Khan Higher Secondary School",
    degree: "Intermediate (FSc/A-Levels equivalent)",
    period: "Completed",
    location: "Hyderabad, Sindh",
    details: "Grade: 91.6% | Board: Aga Khan University Examination Board",
    type: "school",
    icon: "school",
  },
  {
    institution: "Public School Hyderabad",
    degree: "Matriculation",
    period: "Completed",
    location: "Hyderabad, Sindh",
    details: "Grade: 84.5% | Board: Aga Khan University Examination Board",
    type: "school",
    icon: "bookOpen",
  },
];

export const experience = [
  {
    title: "Co-Founder & Technical Lead",
    company: "Nuqta (joinnuqta.org)",
    period: "2025 – Present",
    type: "startup",
    icon: "sparkles",
    color: "#8A9A5B",
    description: "Co-founded Pakistan's largest student mentorship platform with Zayam. Together, engineered the full-stack web application, recruited and vetted high-achieving mentors, and led community growth.",
    highlights: [
      "Co-founded Nuqta with Zayam & collaboratively built full-stack platform",
      "Recruited, interviewed & onboarded verified student mentors",
      "Built Student, Mentor, and Admin real-time management dashboards",
      "Fostered a thriving mentorship community for aspiring learners across Pakistan",
    ],
  },
  {
    title: "Contract Sales Representative",
    company: "State Life Insurance Corporation of Pakistan",
    period: "2026",
    type: "professional",
    icon: "briefcase",
    color: "#C2A878",
    description: "Worked in a professional B2C sales environment, managing client relationships and driving conversions through effective communication and negotiation.",
    highlights: [
      "Client communication & relationship management",
      "Negotiation & persuasion in a professional setting",
      "Built confidence in public-facing, high-stakes conversations",
      "Developed real-world business and sales acumen",
    ],
  },
];

export const leadership = [
  {
    title: "Captain, Student Council",
    organization: "Aga Khan Higher Secondary School Hyderabad",
    icon: "award",
    color: "#8A9A5B",
    description: "Led a student body of 1,800+ students. Coordinated council responsibilities, organized initiatives, and represented student interests at the institutional level.",
    impact: "1,800+ students represented",
  },
  {
    title: "President, English Club",
    organization: "Aga Khan Higher Secondary School Hyderabad",
    icon: "mic",
    color: "#B6BE9C",
    description: "Led club activities and organized English-language events that boosted communication skills, public speaking, and confidence among peers.",
    impact: "Organized 5+ events",
  },
  {
    title: "Team Leader",
    organization: "Multiple Academic Projects",
    icon: "users",
    color: "#66734F",
    description: "Served as team leader across multiple academic projects including the Civics project. Coordinated task distribution, managed timelines, and ensured quality delivery.",
    impact: "Led cross-functional teams",
  },
  {
    title: "Founder & CEO",
    organization: "ZBM Lifestyle",
    icon: "store",
    color: "#A56F5A",
    description: "Founded and operated an e-commerce lifestyle brand for one year. Managed product sourcing, branding, marketing, and customer interactions. Closed to prioritize FAST — proof of academic discipline.",
    impact: "1 year of operations",
  },
];

export const projects = [
  {
    title: "FocusFlow",
    tagline: "Windows productivity desktop app",
    description: "A Windows .exe productivity application designed to help users improve focus, track study sessions, and build better habits through structured work intervals.",
    tech: ["C++", "Windows API", "SFML"],
    features: ["Focus timer & session tracking", "Study habit analytics", "Minimal distraction UI", "Desktop native performance"],
    category: "Desktop App",
    icon: "clock",
    color: "#8A9A5B",
    github: "https://github.com/abzakir",
    status: "Shipped",
  },
  {
    title: "Hand Gesture PC Controller",
    tagline: "Control your PC with hand gestures",
    description: "Real-time computer vision system using Python and MediaPipe to recognize hand gestures and translate them into system control inputs — no mouse, no keyboard.",
    tech: ["Python", "MediaPipe", "OpenCV", "Computer Vision"],
    features: ["Real-time hand tracking", "Gesture-to-command mapping", "Mouse & keyboard control", "Low-latency pipeline"],
    category: "AI / CV",
    icon: "activity",
    color: "#B6BE9C",
    github: "https://github.com/abzakir",
    status: "Shipped",
  },
  {
    title: "TumblePop Clone",
    tagline: "Classic arcade game in C++ with OOP",
    description: "A feature-complete clone of the classic TumblePop arcade game, built from scratch in C++ using object-oriented design principles and SFML for graphics.",
    tech: ["C++", "SFML", "OOP", "Game Loop"],
    features: ["Collision detection system", "Game state management", "Enemy AI patterns", "Score & progression logic"],
    category: "Game Dev",
    icon: "gamepad",
    color: "#66734F",
    github: "https://github.com/abzakir",
    status: "Shipped",
  },
  {
    title: "Metal Slug Clone",
    tagline: "Side-scrolling shooter in C++ OOP",
    description: "A side-scrolling run-and-gun game inspired by Metal Slug, built in C++ with a full OOP architecture — including enemy systems, animations, and level design.",
    tech: ["C++", "SFML", "OOP", "Animation System"],
    features: ["Side-scrolling level system", "Enemy AI & pathfinding", "Character animation FSM", "Projectile & hitbox system"],
    category: "Game Dev",
    icon: "target",
    color: "#A56F5A",
    github: "https://github.com/abzakir",
    status: "Shipped",
  },
  {
    title: "Web Design Projects",
    tagline: "Responsive frontend interfaces",
    description: "A collection of modern, responsive web design projects showcasing frontend skills — clean layouts, visual design sensibility, and mobile-first development.",
    tech: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    features: ["Mobile-first layouts", "CSS animations & transitions", "Clean visual hierarchy", "Cross-browser compatibility"],
    category: "Frontend",
    icon: "layout",
    color: "#C2A878",
    github: "https://github.com/abzakir",
    status: "Ongoing",
  },
];

export const achievements = [
  {
    title: "World AI Competition for Youth",
    subtitle: "Participant — 2020 & 2021",
    description: "Participated twice in this prestigious global youth AI competition, showcasing AI projects and competing on an international level.",
    category: "AI",
    icon: "cpu",
    color: "#B6BE9C",
    year: "2020–2021",
    type: "Competition",
    image: "/waicy-logo.webp",
  },
  {
    title: "AKESP MUN",
    subtitle: "Honourable Mention",
    description: "Received Honourable Mention at the AKESP Model United Nations conference for outstanding debate, diplomacy, and resolution writing.",
    category: "MUN",
    icon: "globe",
    color: "#8A9A5B",
    year: "2022",
    type: "Award",
  },
  {
    title: "HDMUN",
    subtitle: "Honourable Mention",
    description: "Recognized with Honourable Mention at HDMUN for strong committee performance and diplomatic skills.",
    category: "MUN",
    icon: "globe",
    color: "#66734F",
    year: "2022",
    type: "Award",
  },
  {
    title: "Open House — Water Monitoring System",
    subtitle: "Participation Certificate",
    description: "Built and presented a Water Monitoring System focused on sea monitoring, earthquake detection, and environmental awareness.",
    category: "STEM",
    icon: "droplet",
    color: "#B6BE9C",
    year: "2022",
    type: "Exhibition",
  },
  {
    title: "STEAM Competition — AI Skin Analysis",
    subtitle: "Category: Artificial Intelligence",
    description: "Developed an AI-powered skin analysis model, trained and deployed for the STEAM Competition organized by the Regional Directorate in collaboration with Government of Sindh.",
    category: "AI",
    icon: "flask",
    color: "#C2A878",
    year: "2023",
    type: "Competition",
  },
  {
    title: "All Sindh Youth Spelling Bee",
    subtitle: "Participant",
    description: "Competed in the All Sindh Youth Spelling Bee Competition, representing English language proficiency at provincial level.",
    category: "Language",
    icon: "book",
    color: "#A56F5A",
    year: "2022",
    type: "Competition",
  },
];

export const timeline = [
  {
    year: "2020",
    title: "First Steps in AI",
    description: "Participated in the World AI Competition for Youth — my first real exposure to artificial intelligence and competitive tech.",
    icon: "cpu",
    color: "#B6BE9C",
  },
  {
    year: "2021",
    title: "AI Competition (Again)",
    description: "Returned to the World AI Competition for Youth with more depth and confidence. Back-to-back participation at an international level.",
    icon: "repeat",
    color: "#8A9A5B",
  },
  {
    year: "2022",
    title: "Leadership & Recognition",
    description: "Elected Captain of Student Council (1,800+ students), President of English Club, and earned Honourable Mentions at AKESP MUN and HDMUN.",
    icon: "award",
    color: "#C2A878",
  },
  {
    year: "2023",
    title: "Builder Mode",
    description: "STEAM Competition win with AI Skin Analysis. Founded ZBM Lifestyle e-commerce brand.",
    icon: "zap",
    color: "#66734F",
  },
  {
    year: "2025",
    title: "FAST NUCES — Chapter Begins",
    description: "Enrolled in BS Computer Science at FAST National University, Islamabad. Started building real software: games in C++, computer vision in Python.",
    icon: "graduation",
    color: "#A56F5A",
  },
  {
    year: "2025",
    title: "Shipping Real Projects",
    description: "FocusFlow desktop app, Hand Gesture Controller, Metal Slug & TumblePop clones. Deep dives into OOP, systems programming, and AI tooling.",
    icon: "code",
    color: "#B6BE9C",
  },
  {
    year: "2026",
    title: "Professional Sales",
    description: "Began contract role at State Life Insurance. Enhancing real-world negotiation, relationship management, and B2C communication.",
    icon: "briefcase",
    color: "#C2A878",
  },
  {
    year: "→ 2029",
    title: "The Road Ahead",
    description: "Building toward a career in software engineering and AI. Every project, every line of code, every challenge is preparation for what comes next.",
    icon: "sparkles",
    color: "#8A9A5B",
  },
];

export const nuqtaData = {
  name: "Nuqta",
  logo: "/icon.png",
  website: "https://www.joinnuqta.org",
  tagline: "Building the Future of Student Mentorship in Pakistan",
  shortDesc: "Nuqta is an EdTech startup I co-founded with Zayam and fellow Computer Science students from FAST NUCES Islamabad. Together, we built Pakistan's largest student mentorship platform to bridge the gap between high-achieving students and those seeking guidance.",
  fullDesc: [
    "Nuqta is an EdTech startup I co-founded with Zayam and fellow Computer Science students from FAST NUCES Islamabad. Together, we designed and built the entire platform to bridge the gap between high-achieving students and those seeking guidance by creating Pakistan's largest student mentorship platform.",
    "The platform connects students with verified mentors who have excelled in board examinations, university admissions, scholarships, internships, competitive programming, freelancing, entrepreneurship, and career development.",
    "Students receive personalized mentorship, academic guidance, career advice, and access to a growing community of ambitious learners committed to achieving their goals."
  ],
  mission: {
    highlight: "Every student deserves access to the right guidance at the right time.",
    text: "Nuqta exists to connect ambitious students with mentors who have already walked the path they aspire to follow, making quality mentorship accessible, trustworthy, and impactful for students across Pakistan."
  },
  impactStats: [
    { title: "Students Supported", badge: "Growing", icon: "GraduationCap", color: "#8A9A5B" },
    { title: "Verified Mentors", badge: "Growing", icon: "UserCheck", color: "#B6BE9C" },
    { title: "Growing Community", badge: "Expanding", icon: "Globe", color: "#C2A878" },
    { title: "Live Platform", badge: "Live Now", icon: "Rocket", color: "#93A66D" },
  ],
  features: [
    { name: "Verified Mentors", desc: "Vetted top achievers with proven academic and industry track records", icon: "ShieldCheck" },
    { name: "Student Dashboard", desc: "Intuitive portal for booking, tracking progress, and accessing resources", icon: "LayoutDashboard" },
    { name: "Mentor Dashboard", desc: "Streamlined schedule management and session tracking tools", icon: "CalendarCheck" },
    { name: "Admin Dashboard", desc: "Centralized control panel for system oversight, verification, and analytics", icon: "Sliders" },
    { name: "Personalized Mentorship", desc: "1-on-1 tailor-made guidance aligned with individual goals", icon: "Sparkles" },
    { name: "Academic Roadmaps", desc: "Step-by-step guidance for board exams, SATs, ECAT, and university entrance", icon: "Compass" },
    { name: "Career Guidance", desc: "Insights into freelancing, internships, software engineering, and startups", icon: "Briefcase" },
    { name: "Community Support", desc: "Peer-to-peer learning network and collaborative student groups", icon: "Users" },
    { name: "Secure Authentication", desc: "Bank-grade data privacy and secure user authentication", icon: "Lock" },
    { name: "Real-Time Platform", desc: "Instant notifications, status updates, and interactive sessions", icon: "Zap" },
    { name: "Mentor Profiles", desc: "Detailed portfolio profiles highlighting expertise and achievements", icon: "User" },
    { name: "Mentorship Session Booking", desc: "Seamless calendar integration and automated session scheduling", icon: "Clock" },
  ],
  techStack: [
    { name: "React", category: "Frontend", color: "#61DAFB" },
    { name: "Next.js", category: "Framework", color: "#FFFFFF" },
    { name: "Node.js", category: "Runtime", color: "#339933" },
    { name: "Express.js", category: "Backend", color: "#828282" },
    { name: "MongoDB", category: "Database", color: "#47A248" },
    { name: "Tailwind CSS", category: "Styling", color: "#06B6D4" },
    { name: "REST APIs", category: "Architecture", color: "#8A9A5B" },
    { name: "Git", category: "Version Control", color: "#F05032" },
    { name: "GitHub", category: "Repository", color: "#A8B9CC" },
  ],
  timeline: [
    { milestone: "Idea Validated", done: true, desc: "Market research & student demand assessment" },
    { milestone: "Core Team Formed", done: true, desc: "Co-founded by Zayam & Zakir with CS students from FAST NUCES" },
    { milestone: "Mentor Recruitment", done: true, desc: "Onboarding top academic & technical talent" },
    { milestone: "Community Established", done: true, desc: "Initial cohort of ambitious learners" },
    { milestone: "Full-Stack Platform Developed", done: true, desc: "Built collaboratively by Zayam & Zakir" },
    { milestone: "Student Dashboard", done: true, desc: "Interactive student portal shipped" },
    { milestone: "Mentor Dashboard", done: true, desc: "Mentor availability & session control" },
    { milestone: "Admin Dashboard", done: true, desc: "Verification and ecosystem management" },
    { milestone: "Authentication & Database Integration", done: true, desc: "Secure DB schemas and auth flows" },
    { milestone: "Website Officially Launched", done: true, isHighlight: true, desc: "Live at joinnuqta.org" },
  ],
  launchNote: "Nuqta has officially launched and is actively connecting students with experienced mentors across Pakistan. We continue improving the platform by introducing new features, enhancing user experience, and expanding our mentor network to make quality guidance accessible for every student.",
  currentStatus: {
    status: "LIVE",
    phase: "Growth & Feature Development",
    focus: [
      "Expanding mentor network",
      "Improving user experience",
      "Scaling the student community",
      "Building advanced mentorship features"
    ]
  },
  vision: {
    quote: "Every successful student has a story. Nuqta exists to ensure every aspiring student has someone to learn from.",
    desc: "Our long-term vision is to become Pakistan's largest student mentorship ecosystem, empowering millions of learners to make informed academic and career decisions through trusted guidance, meaningful mentorship, and a thriving community of future leaders."
  },
  founderNote: {
    title: "From the Founder",
    quote: "I believe talent exists everywhere, but guidance doesn't. Nuqta is my attempt to change that.",
    author: "Zakir",
    role: "Co-Founder, Nuqta"
  }
};

